### ISSUE TITLE
Python 2 support still showing on PyPi

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/pyelectro#13]
https://pypi.org/project/pyelectro/ shows support for python 2.7 even though this was removed from https://github.com/NeuralEnsemble/pyelectro/blob/master/setup.py

**Comment by sanjayankur31** [comment]
I think I missed removing that in the PR, the tagged commit still has 2.7 in it:

https://github.com/NeuralEnsemble/pyelectro/tree/9cb03a16958943144b9d30db96737316f7db2130

Cutting a new release from master *should* fix it?

**Comment by pgleeson** [comment]
Ok, think it was my fault, I merged the pr, then made a release from my local version without pulling the changes...

**Comment by pgleeson** [comment]
Ok, this is fixed now on https://pypi.org/project/pyelectro/
